import time
from sys import argv
print(argv)
print(type(argv))
print()
time.sleep(1)
print(argv[0])
print(argv[1])
print(argv[2])
print(argv[3])
print()
print("Data-Types")
print(type(argv[0]))
print(type(argv[1]))
print(type(argv[2]))
print(type(argv[3]))
print("end of application")